from django.urls import path, include
from myapp import views

urlpatterns = [
    path('', views.login, name='login'),
    path("signup", views.handlesignup, name="handleSignup"),
    path("login", views.handlelogin, name="handleLogin"),
    path("logout", views.handlelogout, name="handlelogout"),
    path("profile", views.profile, name="profile"),
    path("image", views.image, name="image"),
    path('home', views.home, name='home'),
    path('search', views.search, name='search'),
    path('report', views.report, name='report'),
    path('messages', views.messages, name='messages'),
    path('settings', views.settings, name='settings'),
    path('create', views.create, name='create'),
    path('changeusername', views.changeusername, name='changeusername'),
    path('changepwd', views.changepwd, name='changepwd'),
    path('deactivate/<int:id>', views.deactivate, name='deactivate'),
    path('delete_post <int:post_id>', views.delete_post, name='delete_post'),
    path('profile <str:name>', views.profile_view, name='profile_view'),
    path('bio', views.editbio, name='bio'),
    path('like <int:post_id>', views.like, name='like'),
    path('viewlikes <int:post_id>', views.viewlikes, name='viewlikes'),
    path('comments <int:post_id>',views.comments,name='comments'),
    path('viewfriends', views.viewfriends, name="viewfriends"),
    path('friends <str:name>', views.profile_view, name='friends'),
    path('message <str:name>', views.message, name="message"),
    path('chat', views.chat, name="chat"),
    path('ajax_messages_refresh/<str:sender>/<str:reciever>/', views.ajax_messages_refresh, name='ajax_messages_refresh'),
    path('toggle_private_account', views.toggle_private_account, name='toggle_private_account'),
    path('accept_follow_request <str:name>', views.accept_follow_request, name='accept_follow_request'),
    path('reject_follow_request <str:name>', views.reject_follow_request, name='reject_follow_request'),
]