# Generated by Django 4.1.7 on 2023-11-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_account',
            field=models.BooleanField(default=False),
        ),
    ]
